=== Hyper-TH/Enterprise-Sys-Info-Arch/week2/invoice.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="invoice">
		<xs:complexType>
		<xs:sequence>
			<xs:element name="invoiceNumber" type="xs:positiveInteger"/>
			<xs:element name="invoiceDate" type="xs:date"/>
			<xs:element name="invoiceTotal" type="xs:decimal"/>
			<xs:element name="issuedBy" type="xs:string"/>
			
			<xs:element name="billTo">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="name" type="xs:string"/>
						<xs:element name="address">
						<xs:complexType>
							<xs:sequence>
								<xs:element name="number" type="xs:positiveInteger"/>
								<xs:element name="street" type="xs:string"/>
								<xs:element name="city" type="xs:string"/>
							</xs:sequence>
						</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			
			<xs:element name="item" maxOccurs="unbounded" minOccurs="1">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="name" type="xs:string"/>
						<xs:element name="quantity" type="xs:positiveInteger"/>
						<xs:element name="price" type="xs:decimal"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			
			<xs:element name="paymentInformation" type="xs:string"/>
		</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== Hyper-TH/Enterprise-Sys-Info-Arch/week2/invoice.xml
<?xml version="1.0"?>
<invoice xmlns="http://www.tudublin.ie"
		 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		 xsi:schemaLocation="http://www.tudublin.ie invoice.xsd">
	
	<invoiceNumber>1</invoiceNumber>
	<invoiceDate>2001-10-06</invoiceDate>
	<invoiceTotal>120.00</invoiceTotal>
	<issuedBy>Twila</issuedBy>
	<billTo>
		<name>John</name>
		<address>
			<number>1</number>
			<street>George St</street>
			<city>Dublin</city>
		</address>
	</billTo>
	<item>
		<name>Philips USB 64GB</name>
		<quantity>2</quantity>
		<price>20</price>
	</item>
	<item>
		<name>Instax Mini 11</name>
		<quantity>1</quantity>
		<price>80</price>
	</item>
	<paymentInformation>No additional info</paymentInformation>
</invoice>
